// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("../lib/R.bs.js");

function Checkbox(Props) {
  var checked = Props.checked;
  var onChange = Props.onChange;
  var label = Props.label;
  var name = Props.name;
  return React.createElement("label", {
              className: "checkbox"
            }, React.createElement("input", {
                  checked: checked,
                  name: name,
                  type: "checkbox",
                  onChange: onChange
                }), R$Condorcet.s(label));
}

var make = Checkbox;

exports.make = make;
/* react Not a pure module */
