// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function Link(Props) {
  var linkTo = Props.linkTo;
  var $staropt$star = Props.className;
  var children = Props.children;
  var className = $staropt$star !== undefined ? $staropt$star : "";
  var onClick = function (evt) {
    evt.preventDefault();
    return ReasonReactRouter.push(linkTo);
  };
  return React.createElement("a", {
              className: className,
              href: linkTo,
              onClick: onClick
            }, children);
}

var make = Link;

exports.make = make;
/* react Not a pure module */
