// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("../lib/R.bs.js");

function Toggle(Props) {
  Props.on;
  var onClick = Props.onClick;
  var label = Props.label;
  var btn = React.createElement("button", {
        className: "button button-sm",
        onClick: onClick
      }, React.createElement("i", {
            className: "fas fa-power-off"
          }));
  if (label !== undefined) {
    return React.createElement("div", undefined, React.createElement("label", undefined, R$Condorcet.s(label)), React.createElement("div", {
                    className: "m-t-sm"
                  }, btn));
  } else {
    return btn;
  }
}

var make = Toggle;

exports.make = make;
/* react Not a pure module */
