// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Data$Condorcet = require("./Data.bs.js");

var protocol = (
  process.env.PROTOCOL
);

var host = (
  process.env.HOST
);

var baseUrl = protocol + ("://" + host);

function fetchPoll(id, cb) {
  fetch(baseUrl + ("/api/v1/polls/" + id)).then((function (prim) {
            return prim.json();
          })).then((function (json) {
          var poll = Data$Condorcet.Decode.dPoll(json);
          return Promise.resolve(Curry._1(cb, (function (param) {
                            return poll;
                          })));
        }));
  return /* () */0;
}

function fetchResult(id, cb) {
  fetch(baseUrl + ("/api/v1/polls/" + (id + "/results"))).then((function (prim) {
            return prim.json();
          })).then((function (json) {
          var result = Data$Condorcet.Decode.dResult(json);
          return Promise.resolve(Curry._1(cb, (function (param) {
                            return result;
                          })));
        }));
  return /* () */0;
}

function fetchManageResult(manageToken, cb) {
  fetch(baseUrl + ("/api/v1/polls/" + (manageToken + "/manage"))).then((function (prim) {
            return prim.json();
          })).then((function (json) {
          var result = Data$Condorcet.Decode.dResult(json);
          return Promise.resolve(Curry._1(cb, (function (param) {
                            return result;
                          })));
        }));
  return /* () */0;
}

function createPoll(poll) {
  var payload = Data$Condorcet.encodePollPost(poll);
  return fetch(baseUrl + "/api/v1/polls/", Fetch.RequestInit.make(/* Post */2, {
                        "Content-Type": "application/json"
                      }, Caml_option.some(JSON.stringify(payload)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                var match = Curry._1(Data$Condorcet.Decode.dPollOrErrors, json);
                if (match.tag) {
                  return Promise.resolve(match[0]);
                } else {
                  var errors = match[0];
                  var match$1 = errors.errors.choices;
                  var choiceErrors = match$1 !== undefined ? match$1 : /* [] */0;
                  var match$2 = errors.errors.question;
                  var questionErrors = match$2 !== undefined ? match$2 : /* [] */0;
                  var showErrors = $$Array.of_list(Pervasives.$at(choiceErrors, questionErrors)).join(", ");
                  alert(showErrors);
                  return Promise.resolve(undefined);
                }
              }));
}

function submitPoll(id, response) {
  var payload = Data$Condorcet.encodeResponsePost(response);
  return fetch(baseUrl + ("/api/v1/polls/" + (id + "/respond")), Fetch.RequestInit.make(/* Post */2, {
                      "Content-Type": "application/json"
                    }, Caml_option.some(JSON.stringify(payload)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                return prim.json();
              }));
}

exports.protocol = protocol;
exports.host = host;
exports.baseUrl = baseUrl;
exports.fetchPoll = fetchPoll;
exports.fetchResult = fetchResult;
exports.fetchManageResult = fetchManageResult;
exports.createPoll = createPoll;
exports.submitPoll = submitPoll;
/* protocol Not a pure module */
