// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./R.bs.js");
var CopyToClipboard$Condorcet = require("./CopyToClipboard.bs.js");

function CopyableLink(Props) {
  var link = Props.link;
  var ignoreMe = function (param) {
    console.log("some string");
    return /* () */0;
  };
  return React.createElement(CopyToClipboard$Condorcet.make, {
              text: link,
              onCopy: ignoreMe,
              children: React.createElement("div", {
                    className: "copyable-link"
                  }, R$Condorcet.s(link))
            });
}

var make = CopyableLink;

exports.make = make;
/* react Not a pure module */
