// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var R$Condorcet = require("./R.bs.js");
var CopyToClipboard$Condorcet = require("./CopyToClipboard.bs.js");

function CopyableLink(Props) {
  var link = Props.link;
  var match = React.useState((function () {
          return false;
        }));
  var setCopied = match[1];
  var ignoreMe = function (param) {
    Curry._1(setCopied, (function (_state) {
            return true;
          }));
    setTimeout((function (param) {
            return Curry._1(setCopied, (function (_state) {
                          return false;
                        }));
          }), 3000);
    return /* () */0;
  };
  return React.createElement(CopyToClipboard$Condorcet.make, {
              text: link,
              onCopy: ignoreMe,
              children: React.createElement("div", undefined, React.createElement("div", {
                        className: "copyable-link"
                      }, R$Condorcet.s(link)), match[0] ? React.createElement("span", {
                          className: "copied"
                        }, R$Condorcet.s("Copied to clipboard!")) : null)
            });
}

var make = CopyableLink;

exports.make = make;
/* react Not a pure module */
