// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./R.bs.js");

function CopyableLink(Props) {
  var link = Props.link;
  var copyLink = function (param) {
    console.log(link);
    return /* () */0;
  };
  return React.createElement("div", {
              className: "copyable-link",
              onClick: copyLink
            }, R$Condorcet.s(link));
}

var make = CopyableLink;

exports.make = make;
/* react Not a pure module */
