// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./lib/R.bs.js");

function Done(Props) {
  return React.createElement("div", {
              className: "page"
            }, React.createElement("h3", undefined, R$Condorcet.s("Response successfully submitted")));
}

var make = Done;

exports.make = make;
/* react Not a pure module */
