// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./lib/R.bs.js");
var Link$Condorcet = require("./ui/Link.bs.js");

function Done(Props) {
  return React.createElement("div", {
              className: "page"
            }, React.createElement("h2", undefined, R$Condorcet.s("Response successfully submitted.")), React.createElement(Link$Condorcet.make, {
                  linkTo: "/",
                  className: "centered",
                  children: R$Condorcet.s("Go to Homepage")
                }));
}

var make = Done;

exports.make = make;
/* react Not a pure module */
