// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Api$Condorcet = require("./lib/Api.bs.js");
var EditResults$Condorcet = require("./EditResults.bs.js");

function EditResultsPage(Props) {
  var manageToken = Props.manageToken;
  var notify = Props.notify;
  var match = React.useState((function () {
          return ;
        }));
  var setResult = match[1];
  var result = match[0];
  React.useEffect((function () {
          Api$Condorcet.fetchManageResult(manageToken, setResult);
          return ;
        }), ([]));
  if (result !== undefined) {
    return React.createElement(EditResults$Condorcet.make, {
                notify: notify,
                result: result
              });
  } else {
    return null;
  }
}

var make = EditResultsPage;

exports.make = make;
/* react Not a pure module */
