// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./lib/R.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function Home(Props) {
  return React.createElement("div", {
              className: "page"
            }, React.createElement("h3", {
                  className: "centered"
                }, R$Condorcet.s("Make Better Group Decisions")), React.createElement("p", {
                  className: "centered"
                }, R$Condorcet.s("Use Poller to make group decisions using ranked voting.")), React.createElement("p", {
                  className: "centered"
                }, R$Condorcet.s("Get results for Instant Runoffs, Borda Counts, the Condorcet method, and simple plurality elections.")), React.createElement("br", undefined), React.createElement("div", {
                  className: "centered"
                }, React.createElement("button", {
                      className: "button button-mdlg",
                      onClick: (function (param) {
                          return ReasonReactRouter.push("/new");
                        })
                    }, R$Condorcet.s("Create a Poll"))), React.createElement("br", undefined), React.createElement("p", {
                  className: "centered"
                }, React.createElement("a", {
                      className: "centered",
                      onClick: (function (param) {
                          return ReasonReactRouter.push("/why");
                        })
                    }, R$Condorcet.s("What are the advantages compared to standard elections?"))));
}

var make = Home;

exports.make = make;
/* react Not a pure module */
