// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./R.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function Home(Props) {
  return React.createElement("div", {
              className: "page"
            }, React.createElement("h3", {
                  className: "centered"
                }, R$Condorcet.s("Make Better Group Decisions")), React.createElement("p", undefined, R$Condorcet.s("Use Poller to make ranked polls with alternative election schemes.")), React.createElement("p", undefined, R$Condorcet.s("Get results for Instant Runoff, Borda Count, and Simple Plurality elections.")), React.createElement("br", undefined), React.createElement("div", {
                  className: "centered"
                }, React.createElement("button", {
                      className: "button button-mdlg",
                      onClick: (function (param) {
                          return ReasonReactRouter.push("/new");
                        })
                    }, R$Condorcet.s("Create a Poll"))), React.createElement("br", undefined));
}

var make = Home;

exports.make = make;
/* react Not a pure module */
