// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./lib/R.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Notifications$Condorcet = require("./Notifications.bs.js");

function Layout(Props) {
  var notifications = Props.notifications;
  var children = Props.children;
  return React.createElement("div", undefined, React.createElement(Notifications$Condorcet.make, {
                  notifications: notifications
                }), React.createElement("div", {
                  className: "header",
                  onClick: (function (param) {
                      return ReasonReactRouter.push("/");
                    })
                }, R$Condorcet.s("Poller.io")), React.createElement("div", {
                  className: "content"
                }, children));
}

var make = Layout;

exports.make = make;
/* react Not a pure module */
