// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./R.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Constants$Condorcet = require("./Constants.bs.js");
var PollResults$Condorcet = require("./PollResults.bs.js");
var CopyableLink$Condorcet = require("./CopyableLink.bs.js");

function ManagePoll(Props) {
  var result = Props.result;
  var match = result.poll.id;
  var tmp;
  if (match !== undefined) {
    var id = match;
    tmp = React.createElement("div", {
          className: "centered"
        }, React.createElement("button", {
              className: "button",
              onClick: (function (param) {
                  return ReasonReactRouter.push("/take-poll/" + id);
                })
            }, R$Condorcet.s("Take the Poll Yourself")));
  } else {
    tmp = null;
  }
  var match$1 = result.poll.manageToken;
  var match$2 = result.poll.id;
  return React.createElement("div", {
              className: "page"
            }, React.createElement("h3", {
                  className: "centered"
                }, R$Condorcet.s("Poll: " + result.poll.question)), tmp, React.createElement("div", undefined, React.createElement("h3", undefined, R$Condorcet.s("Links:")), match$1 !== undefined ? React.createElement("div", {
                        className: "link-holder"
                      }, React.createElement("p", undefined, R$Condorcet.s("Manage Poll Link:")), React.createElement(CopyableLink$Condorcet.make, {
                            link: Constants$Condorcet.host + ("/manage-poll/" + match$1)
                          }), React.createElement("p", undefined, React.createElement("b", undefined, R$Condorcet.s("This link is a password. Don't lose it!")))) : null, match$2 !== undefined ? React.createElement("div", {
                        className: "link-holder"
                      }, React.createElement("p", undefined, R$Condorcet.s("Take Poll Link:")), React.createElement(CopyableLink$Condorcet.make, {
                            link: Constants$Condorcet.host + ("/take-poll/" + match$2)
                          })) : null), React.createElement("div", undefined, React.createElement("h3", undefined, R$Condorcet.s("Results:")), React.createElement(PollResults$Condorcet.make, {
                      result: result
                    })));
}

var make = ManagePoll;

exports.make = make;
/* react Not a pure module */
