// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Api$Condorcet = require("./lib/Api.bs.js");
var ManagePoll$Condorcet = require("./ManagePoll.bs.js");

function ManagePollPage(Props) {
  var manageToken = Props.manageToken;
  var match = React.useState((function () {
          return ;
        }));
  var setResult = match[1];
  var result = match[0];
  React.useEffect((function () {
          Api$Condorcet.fetchManageResult(manageToken, setResult);
          return ;
        }), ([]));
  if (result !== undefined) {
    return React.createElement(ManagePoll$Condorcet.make, {
                result: result
              });
  } else {
    return null;
  }
}

var make = ManagePollPage;

exports.make = make;
/* react Not a pure module */
