// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var R$Condorcet = require("./lib/R.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Constants$Condorcet = require("./lib/Constants.bs.js");
var PollResults$Condorcet = require("./PollResults.bs.js");
var CopyableLink$Condorcet = require("./ui/CopyableLink.bs.js");

function ManagePoll(Props) {
  var result = Props.result;
  var match = result.poll.id;
  var match$1 = result.poll.manageToken;
  var match$2 = result.poll.id;
  if (match !== undefined && match$1 !== undefined && match$2 !== undefined) {
    var pollId = match;
    var manageToken = match$1;
    var takeToken = match$2;
    return React.createElement("div", {
                className: "page"
              }, React.createElement("h3", {
                    className: "centered"
                  }, R$Condorcet.s(result.poll.question)), React.createElement("div", {
                    className: "centered"
                  }, React.createElement("button", {
                        className: "button",
                        onClick: (function (param) {
                            return ReasonReactRouter.push("/take-poll/" + pollId);
                          })
                      }, R$Condorcet.s("Take the Poll Yourself"))), React.createElement("div", {
                    className: "link-holder"
                  }, React.createElement("h4", undefined, R$Condorcet.s("Manage Poll Link")), React.createElement(CopyableLink$Condorcet.make, {
                        link: Constants$Condorcet.host + ("/manage-poll/" + manageToken)
                      }), React.createElement("p", undefined, React.createElement("b", undefined, R$Condorcet.s("This link is a password. Don't lose it!")))), React.createElement("div", {
                    className: "link-holder"
                  }, React.createElement("h4", undefined, R$Condorcet.s("Take Poll Link")), React.createElement(CopyableLink$Condorcet.make, {
                        link: Constants$Condorcet.host + ("/take-poll/" + takeToken)
                      })), React.createElement(PollResults$Condorcet.make, {
                    result: result
                  }), React.createElement("div", undefined, React.createElement("button", {
                        className: "button",
                        onClick: (function (param) {
                            return ReasonReactRouter.push("/manage-poll/" + (manageToken + "/edit-results"));
                          })
                      }, R$Condorcet.s("Edit Results"))));
  } else {
    return null;
  }
}

var make = ManagePoll;

exports.make = make;
/* react Not a pure module */
