// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var R$Condorcet = require("./lib/R.bs.js");

function Notifications(Props) {
  var notifications = Props.notifications;
  var renderNotification = function (idx, n) {
    var className = "notification " + n.t;
    return React.createElement("div", {
                key: String(idx),
                className: className
              }, R$Condorcet.s(n.text));
  };
  return React.createElement("div", {
              className: "notifications"
            }, $$Array.of_list(List.mapi(renderNotification, notifications)));
}

var make = Notifications;

exports.make = make;
/* react Not a pure module */
