// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var R$Condorcet = require("./lib/R.bs.js");

function PollResponseDetails(Props) {
  var result = Props.result;
  var renderResponseCount = function (count) {
    if (count !== 0) {
      if (count !== 1) {
        return React.createElement("p", undefined, R$Condorcet.s(String(count) + " responses from:"));
      } else {
        return React.createElement("p", undefined, R$Condorcet.s("1 response from: "));
      }
    } else {
      return React.createElement("p", undefined, R$Condorcet.s("No responses yet"));
    }
  };
  var renderResponseNames = function (responses) {
    var nameList = List.map((function (r) {
            return r.name;
          }), responses);
    if (nameList) {
      return React.createElement("p", undefined, R$Condorcet.s($$Array.of_list(nameList).join(", ")));
    } else {
      return null;
    }
  };
  return React.createElement("div", {
              className: "responses-holder"
            }, renderResponseCount(result.responseCount), renderResponseNames(result.responses));
}

var make = PollResponseDetails;

exports.make = make;
/* react Not a pure module */
