// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var R$Condorcet = require("./lib/R.bs.js");
var Ordinal$Condorcet = require("./lib/Ordinal.bs.js");
var Constants$Condorcet = require("./lib/Constants.bs.js");
var CopyableLink$Condorcet = require("./ui/CopyableLink.bs.js");
var PollResponseDetails$Condorcet = require("./PollResponseDetails.bs.js");

function PollResults(Props) {
  var result = Props.result;
  var $staropt$star = Props.showLink;
  var showLink = $staropt$star !== undefined ? $staropt$star : false;
  var match = React.useState((function () {
          return false;
        }));
  var setFullResults = match[1];
  var showingFullResults = match[0];
  var changeFullRes = function (param) {
    return Curry._1(setFullResults, (function (param) {
                  return !showingFullResults;
                }));
  };
  var renderWinners = function (winnersList) {
    return React.createElement("b", undefined, R$Condorcet.s($$Array.of_list(winnersList).join(", ")));
  };
  var renderRankedResults = function (rankedResults) {
    return React.createElement("div", undefined, $$Array.of_list(List.mapi((function (idx, winners) {
                          return React.createElement("div", {
                                      key: String(idx)
                                    }, React.createElement("i", undefined, React.createElement(Ordinal$Condorcet.make, {
                                              num: idx + 1 | 0
                                            }), R$Condorcet.s(": ")), R$Condorcet.s($$Array.of_list(winners).join(", ")));
                        }), rankedResults)));
  };
  var renderFullBorda = function (resultMap, unit, units) {
    return React.createElement("div", undefined, $$Array.of_list(List.map((function (param) {
                          var res = param.res;
                          var key = param.key;
                          return React.createElement("div", {
                                      key: key,
                                      className: "full-results"
                                    }, React.createElement("i", undefined, R$Condorcet.s(key + ": ")), res !== 1 ? R$Condorcet.s(String(res) + (" " + units)) : R$Condorcet.s(String(res) + (" " + unit)));
                        }), List.sort((function (a, b) {
                              var match = a.res < b.res;
                              var match$1 = a.res === b.res;
                              if (match) {
                                return 1;
                              } else if (match$1) {
                                return 0;
                              } else {
                                return -1;
                              }
                            }), List.map((function (key) {
                                  var match = Js_dict.get(resultMap, key);
                                  if (match !== undefined) {
                                    return {
                                            key: key,
                                            res: match
                                          };
                                  } else {
                                    return {
                                            key: key,
                                            res: 0
                                          };
                                  }
                                }), $$Array.to_list(Object.keys(resultMap)))))));
  };
  var renderFullResult = function (resultMap, unit, units) {
    return React.createElement("div", undefined, $$Array.of_list(List.map((function (key) {
                          var match = Js_dict.get(resultMap, key);
                          var tmp;
                          if (match !== undefined) {
                            var res = match;
                            tmp = res !== 1 ? R$Condorcet.s(String(res) + (" " + units)) : R$Condorcet.s(String(res) + (" " + unit));
                          } else {
                            tmp = null;
                          }
                          return React.createElement("div", {
                                      key: key,
                                      className: "full-results"
                                    }, React.createElement("i", undefined, R$Condorcet.s(key + ": ")), tmp);
                        }), $$Array.to_list(Object.keys(resultMap)))));
  };
  var renderWinnerString = function (lst, typ) {
    return typ + (
            List.length(lst) > 1 ? " winners: " : " winner: "
          );
  };
  var renderResultsLink = function (param) {
    var match = result.poll.id;
    if (match !== undefined) {
      return React.createElement("div", {
                  className: "resuts-link-holder"
                }, React.createElement("p", undefined, React.createElement("b", undefined, R$Condorcet.s("Save this URL to return to restuls:"))), React.createElement(CopyableLink$Condorcet.make, {
                      link: Constants$Condorcet.host + ("/results/" + match)
                    }));
    } else {
      return null;
    }
  };
  var match$1 = result.winners;
  var match$2 = result.winners;
  var match$3 = result.fullResults;
  var tmp;
  if (match$2 !== undefined && match$3 !== undefined) {
    var resultsMap = match$3;
    var winnerMap = match$2;
    var rankedString = renderWinnerString(winnerMap.ranked, "Instant Runoff");
    var bordaString = renderWinnerString(winnerMap.borda, "Borda Count");
    var pluralityString = renderWinnerString(winnerMap.plurality, "Plurality");
    var match$4 = winnerMap.condorcet;
    var match$5 = result.winners;
    tmp = React.createElement("div", undefined, match$4 !== undefined ? React.createElement("p", undefined, R$Condorcet.s("Condorcet Winner: "), React.createElement("b", undefined, R$Condorcet.s(match$4))) : React.createElement("p", undefined, R$Condorcet.s("No Condorcet Winner")), React.createElement("p", undefined, R$Condorcet.s(rankedString), renderWinners(winnerMap.ranked)), showingFullResults ? renderRankedResults(resultsMap.ranked) : null, React.createElement("p", undefined, R$Condorcet.s(bordaString), renderWinners(winnerMap.borda)), showingFullResults ? renderFullBorda(resultsMap.borda, "point", "points") : null, React.createElement("p", undefined, R$Condorcet.s(pluralityString), renderWinners(winnerMap.plurality)), showingFullResults ? renderFullResult(resultsMap.plurality, "first place vote", "first place votes") : null, match$5 !== undefined ? React.createElement("div", {
                className: "m-t-sm"
              }, React.createElement("a", {
                    href: "/why#alternative-methods"
                  }, R$Condorcet.s("What do these results mean?"))) : null);
  } else {
    tmp = null;
  }
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "results-title"
                }, React.createElement("h3", undefined, R$Condorcet.s("Results")), match$1 !== undefined ? React.createElement("button", {
                        className: "button button-sm",
                        onClick: changeFullRes
                      }, R$Condorcet.s(showingFullResults ? "Hide full results" : "Show full results")) : null), tmp, React.createElement(PollResponseDetails$Condorcet.make, {
                  result: result
                }), showLink ? renderResultsLink(/* () */0) : null);
}

var make = PollResults;

exports.make = make;
/* react Not a pure module */
