// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Api$Condorcet = require("./Api.bs.js");
var PollResults$Condorcet = require("./PollResults.bs.js");

function PollResultsPage(Props) {
  var id = Props.id;
  var match = React.useState((function () {
          return ;
        }));
  var setResult = match[1];
  var result = match[0];
  React.useEffect((function () {
          Api$Condorcet.fetchResult(id, setResult);
          return ;
        }), ([]));
  if (result !== undefined) {
    return React.createElement("div", {
                className: "page"
              }, React.createElement(PollResults$Condorcet.make, {
                    result: result
                  }));
  } else {
    return null;
  }
}

var make = PollResultsPage;

exports.make = make;
/* react Not a pure module */
