// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function findIndexOf(arr, x) {
  var i = arr.findIndex((function (x$prime) {
          return Caml_obj.caml_equal(x$prime, x);
        }));
  if (i !== -1) {
    return i;
  } else {
    return Pervasives.failwith("Unable to find `" + (String(x) + ("` in array `" + (String(arr) + "`"))));
  }
}

function insert(arr, value, place) {
  var arr$1 = arr.slice();
  arr$1.splice(typeof place === "number" ? arr$1.length : findIndexOf(arr$1, place[1]), 0, value);
  return arr$1;
}

function reinsert(arr, value, place) {
  var arr$1 = arr.slice();
  var from = findIndexOf(arr$1, value);
  arr$1.splice(from, 1);
  arr$1.splice(typeof place === "number" ? arr$1.length : findIndexOf(arr$1, place[1]), 0, value);
  return arr$1;
}

exports.findIndexOf = findIndexOf;
exports.insert = insert;
exports.reinsert = reinsert;
/* No side effect */
