// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var currentEnv = window.env;

var protocol = currentEnv.protocol;

var host = currentEnv.host;

var indexType = currentEnv.indexType;

exports.currentEnv = currentEnv;
exports.protocol = protocol;
exports.host = host;
exports.indexType = indexType;
/* currentEnv Not a pure module */
