// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var CopyToClipboard = require("../imports/copyToClipboard");

var make = CopyToClipboard.default;

exports.make = make;
/* make Not a pure module */
